#!/usr/bin/env bash
set -euo pipefail

PROFILE="${1:-prod}"

mkdir -p deploy

# ---------- Runtime (Compose) ----------
cat > deploy/.env <<'EOF'
# Runtime/Compose
API_IMAGE=yourusername/api:latest
CLIENT_IMAGE=yourusername/client:latest
ADMIN_CLIENT_IMAGE=yourusername/admin-client:latest

APP_PORT=8080
APP_NAME=api
ACTIVE_PROFILES=prod

DB_HOST=mysql
DB_PORT=3306
DB_NAME=mydb
DB_USERNAME=myuser
DB_PASSWORD=mypassword
DB_ROOT_PASSWORD=rootpassword

PASSWORD_ENCODER_SECRET=change_me
JWT_SECRET=change_me
JWT_ACCESS_EXPIRATION=PT30M
JWT_REFRESH_EXPIRATION=PT12H
INIT_BOOTSTRAP_SERVICE_KEY=change_me

LIVEKIT_API_KEY=change_me
LIVEKIT_API_SECRET=change_me

# Redis / invite links
REDIS_HOST=redis
REDIS_PORT=6379
CLIENT_BASE_URL=http://client

# S3-compatible asset storage. Use a browser-reachable public endpoint in production
# when API responses return presigned asset URLs.
AVATAR_S3_ENDPOINT=https://s3.example.com
AVATAR_S3_REGION=eu
AVATAR_S3_BUCKET=confa-assets
AVATAR_S3_ACCESS_KEY=minioadmin
AVATAR_S3_SECRET_KEY=minioadmin
AVATAR_S3_PATH_STYLE=true

# Message image attachment limits, cleanup, and quotas.
ATTACHMENT_IMAGE_MAX_RAW_UPLOAD_BYTES=5242880
ATTACHMENT_IMAGE_MAX_RAW_EDGE=4096
ATTACHMENT_IMAGE_MAX_RAW_PIXELS=16000000
ATTACHMENT_IMAGE_MAX_DISPLAY_EDGE=1280
ATTACHMENT_IMAGE_MAX_DISPLAY_BYTES=512000
ATTACHMENT_IMAGE_MAX_THUMBNAIL_EDGE=320
ATTACHMENT_IMAGE_MAX_THUMBNAIL_BYTES=81920
ATTACHMENT_IMAGE_MAX_ATTACHMENTS_PER_MESSAGE=1
ATTACHMENT_IMAGE_PRESIGN_TTL_SECONDS=900
ATTACHMENT_IMAGE_CLEANUP_ENABLED=true
ATTACHMENT_IMAGE_PENDING_TTL_SECONDS=3600
ATTACHMENT_IMAGE_DELETED_RETENTION_SECONDS=604800
ATTACHMENT_IMAGE_CLEANUP_BATCH_SIZE=100
ATTACHMENT_IMAGE_CLEANUP_FIXED_DELAY_MS=300000
ATTACHMENT_IMAGE_MAX_PENDING_UPLOADS_PER_USER=20
ATTACHMENT_IMAGE_MAX_PENDING_UPLOADS_PER_SCOPE=200
ATTACHMENT_IMAGE_MAX_STORED_BYTES_PER_USER=1073741824
ATTACHMENT_IMAGE_MAX_STORED_BYTES_PER_SCOPE=2147483648
EOF

# ---------- Build-time (Vite) ----------
cat > deploy/client.build.env <<'EOF'
# Build-time envs for Vite (client)
VITE_API_BASE=http://api:8080
VITE_LIVEKIT_WS_URL=wss://your.example.ru
EOF

echo "Generated deploy/.env, client.build.env for PROFILE=$PROFILE"
